//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureWebConsoleDomain
{
    using AzureWebConsole;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AzureWebConsoleModelContainer : DbContext
    {
        public AzureWebConsoleModelContainer()
            : base(AppSettingsProvider.GetSetting("AzureWebConsoleModelContainer"))
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SteppingNode> SteppingNodes { get; set; }
        public virtual DbSet<AzureVirtualMachine> AzureVirtualMachines { get; set; }
        public virtual DbSet<AzureSubscription> AzureSubscriptions { get; set; }
        public virtual DbSet<TerminalFile> TerminalFiles { get; set; }
        public virtual DbSet<AzureWebConsoleUser> AzureWebConsoleUsers { get; set; }
    }
}
