//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureWebConsoleDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AzureVirtualMachine
    {
        public long Id { get; set; }
        public string SubscriptionId { get; set; }
        public string HostServiceName { get; set; }
        public string Url { get; set; }
        public Nullable<long> Port { get; set; }
        public string OS { get; set; }
        public string DeploymentName { get; set; }
        public string RoleInstanceName { get; set; }
    }
}
