//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureWebConsoleDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AzureSubscription
    {
        public int Id { get; set; }
        public string SubscriptionId { get; set; }
        public string AADTenant { get; set; }
    }
}
