package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-11T20:29:56.271+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IROCatalogExternalExternal_True")
@XmlSeeAlso({ObjectFactory.class, com.windowscloudbackup.protection.v2011_09.ObjectFactory.class, utils.accessmanager.dls.enterprisestorage.internal.microsoft.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_internal_cloudbackup_common_cloudcommon.ObjectFactory.class, com.microsoft.schemas.message.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.windowscloudbackup.cloudcommon.v2011_09.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_internal_cloudbackup_common_async.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_internal_cloudbackup_common_rocatalog.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_internal_cloudbackup_common.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, com.windowscloudbackup.rocatalog.v2011_09.ObjectFactory.class})
public interface IROCatalogExternalExternalTrue {

    @WebResult(name = "GetAllPoliciesForMachineResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetAllPoliciesForMachine", output = "http://tempuri.org/IROCatalogExternal/GetAllPoliciesForMachineResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetAllPoliciesForMachineCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllPoliciesForMachineCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetAllPoliciesForMachineCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllPoliciesForMachineCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetAllPoliciesForMachine", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPoliciesForMachine")
    @WebMethod(operationName = "GetAllPoliciesForMachine", action = "http://tempuri.org/IROCatalogExternal/GetAllPoliciesForMachine")
    @ResponseWrapper(localName = "GetAllPoliciesForMachineResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPoliciesForMachineResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ArrayOfGetPolicyInfoArgs getAllPoliciesForMachine(
        @WebParam(name = "machineArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.GetInfoForMachineArgs machineArgs
    ) throws IROCatalogExternalExternalTrueGetAllPoliciesForMachineCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetAllPoliciesForMachineCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetCurrentEncryptionKeyResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetCurrentEncryptionKey", output = "http://tempuri.org/IROCatalogExternal/GetCurrentEncryptionKeyResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetCurrentEncryptionKeyCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetCurrentEncryptionKeyCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetCurrentEncryptionKeyCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetCurrentEncryptionKeyCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetCurrentEncryptionKey", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrentEncryptionKey")
    @WebMethod(operationName = "GetCurrentEncryptionKey", action = "http://tempuri.org/IROCatalogExternal/GetCurrentEncryptionKey")
    @ResponseWrapper(localName = "GetCurrentEncryptionKeyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrentEncryptionKeyResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.EncryptionKeyEx getCurrentEncryptionKey(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.ReadEncryptionKeyRequest request
    ) throws IROCatalogExternalExternalTrueGetCurrentEncryptionKeyCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetCurrentEncryptionKeyCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/UpdateReplicaClientStamp", output = "http://tempuri.org/IROCatalogExternal/UpdateReplicaClientStampResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueUpdateReplicaClientStampCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/UpdateReplicaClientStampCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueUpdateReplicaClientStampCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/UpdateReplicaClientStampCloudServiceFaultFault")})
    @RequestWrapper(localName = "UpdateReplicaClientStamp", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateReplicaClientStamp")
    @WebMethod(operationName = "UpdateReplicaClientStamp", action = "http://tempuri.org/IROCatalogExternal/UpdateReplicaClientStamp")
    @ResponseWrapper(localName = "UpdateReplicaClientStampResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateReplicaClientStampResponse")
    public void updateReplicaClientStamp(
        @WebParam(name = "ReplicaClientStampArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.UpdateReplicaClientStampArgs replicaClientStampArgs
    ) throws IROCatalogExternalExternalTrueUpdateReplicaClientStampCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueUpdateReplicaClientStampCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "AddMDSetAndMetadataNameValueResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/AddMDSetAndMetadataNameValue", output = "http://tempuri.org/IROCatalogExternal/AddMDSetAndMetadataNameValueResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueAddMDSetAndMetadataNameValueCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddMDSetAndMetadataNameValueCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueAddMDSetAndMetadataNameValueCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddMDSetAndMetadataNameValueCloudServiceFaultFault")})
    @RequestWrapper(localName = "AddMDSetAndMetadataNameValue", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddMDSetAndMetadataNameValue")
    @WebMethod(operationName = "AddMDSetAndMetadataNameValue", action = "http://tempuri.org/IROCatalogExternal/AddMDSetAndMetadataNameValue")
    @ResponseWrapper(localName = "AddMDSetAndMetadataNameValueResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddMDSetAndMetadataNameValueResponse")
    public com.windowscloudbackup.cloudcommon.v2011_09.EntityId addMDSetAndMetadataNameValue(
        @WebParam(name = "metaDataNameValue", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.AddMDSetAndMetadataNameValueArgs metaDataNameValue
    ) throws IROCatalogExternalExternalTrueAddMDSetAndMetadataNameValueCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueAddMDSetAndMetadataNameValueCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetStorageUsageForMachineResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetStorageUsageForMachine", output = "http://tempuri.org/IROCatalogExternal/GetStorageUsageForMachineResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetStorageUsageForMachineCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetStorageUsageForMachineCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetStorageUsageForMachineCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetStorageUsageForMachineCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetStorageUsageForMachine", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStorageUsageForMachine")
    @WebMethod(operationName = "GetStorageUsageForMachine", action = "http://tempuri.org/IROCatalogExternal/GetStorageUsageForMachine")
    @ResponseWrapper(localName = "GetStorageUsageForMachineResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStorageUsageForMachineResponse")
    public com.windowscloudbackup.protection.v2011_09.StorageUsageForMachineResponse getStorageUsageForMachine(
        @WebParam(name = "args", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.protection.v2011_09.StorageUsageForMachineRequest args
    ) throws IROCatalogExternalExternalTrueGetStorageUsageForMachineCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetStorageUsageForMachineCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetPoliciesInfoForDsIdsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetPoliciesInfoForDsIds", output = "http://tempuri.org/IROCatalogExternal/GetPoliciesInfoForDsIdsResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetPoliciesInfoForDsIdsCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetPoliciesInfoForDsIdsCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetPoliciesInfoForDsIdsCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetPoliciesInfoForDsIdsCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetPoliciesInfoForDsIds", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPoliciesInfoForDsIds")
    @WebMethod(operationName = "GetPoliciesInfoForDsIds", action = "http://tempuri.org/IROCatalogExternal/GetPoliciesInfoForDsIds")
    @ResponseWrapper(localName = "GetPoliciesInfoForDsIdsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPoliciesInfoForDsIdsResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ArrayOfGetPolicyInfoArgs getPoliciesInfoForDsIds(
        @WebParam(name = "dsIds", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.protection.v2011_09.GetEntitiesInformationArgs dsIds
    ) throws IROCatalogExternalExternalTrueGetPoliciesInfoForDsIdsCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetPoliciesInfoForDsIdsCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/SetLastAccessTimeForRP", output = "http://tempuri.org/IROCatalogExternal/SetLastAccessTimeForRPResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueSetLastAccessTimeForRPCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/SetLastAccessTimeForRPCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueSetLastAccessTimeForRPCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/SetLastAccessTimeForRPCloudServiceFaultFault")})
    @RequestWrapper(localName = "SetLastAccessTimeForRP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetLastAccessTimeForRP")
    @WebMethod(operationName = "SetLastAccessTimeForRP", action = "http://tempuri.org/IROCatalogExternal/SetLastAccessTimeForRP")
    @ResponseWrapper(localName = "SetLastAccessTimeForRPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetLastAccessTimeForRPResponse")
    public void setLastAccessTimeForRP(
        @WebParam(name = "rpArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.protection.v2011_09.SetLastAccessTimeForRPArgs rpArgs
    ) throws IROCatalogExternalExternalTrueSetLastAccessTimeForRPCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueSetLastAccessTimeForRPCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/DeleteRecoveryPoints", output = "http://tempuri.org/IROCatalogExternal/DeleteRecoveryPointsResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueDeleteRecoveryPointsCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/DeleteRecoveryPointsCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueDeleteRecoveryPointsCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/DeleteRecoveryPointsCloudServiceFaultFault")})
    @RequestWrapper(localName = "DeleteRecoveryPoints", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteRecoveryPoints")
    @WebMethod(operationName = "DeleteRecoveryPoints", action = "http://tempuri.org/IROCatalogExternal/DeleteRecoveryPoints")
    @ResponseWrapper(localName = "DeleteRecoveryPointsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteRecoveryPointsResponse")
    public void deleteRecoveryPoints(
        @WebParam(name = "dsInfo", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.DeleteRecoveryPointsInfoArgs dsInfo
    ) throws IROCatalogExternalExternalTrueDeleteRecoveryPointsCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueDeleteRecoveryPointsCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetAllRecoverableDSForMachineResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetAllRecoverableDSForMachine", output = "http://tempuri.org/IROCatalogExternal/GetAllRecoverableDSForMachineResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetAllRecoverableDSForMachineCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllRecoverableDSForMachineCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetAllRecoverableDSForMachineCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllRecoverableDSForMachineCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetAllRecoverableDSForMachine", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRecoverableDSForMachine")
    @WebMethod(operationName = "GetAllRecoverableDSForMachine", action = "http://tempuri.org/IROCatalogExternal/GetAllRecoverableDSForMachine")
    @ResponseWrapper(localName = "GetAllRecoverableDSForMachineResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRecoverableDSForMachineResponse")
    public com.windowscloudbackup.cloudcommon.v2011_09.ArrayOfEntityId getAllRecoverableDSForMachine(
        @WebParam(name = "machineArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.GetInfoForMachineArgs machineArgs
    ) throws IROCatalogExternalExternalTrueGetAllRecoverableDSForMachineCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetAllRecoverableDSForMachineCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetAllRecoveryPointsForMachineResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForMachine", output = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForMachineResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetAllRecoveryPointsForMachineCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForMachineCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetAllRecoveryPointsForMachineCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForMachineCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetAllRecoveryPointsForMachine", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRecoveryPointsForMachine")
    @WebMethod(operationName = "GetAllRecoveryPointsForMachine", action = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForMachine")
    @ResponseWrapper(localName = "GetAllRecoveryPointsForMachineResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRecoveryPointsForMachineResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.RecoveryPointInfoResponse getAllRecoveryPointsForMachine(
        @WebParam(name = "machineArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.GetInfoForMachineArgs machineArgs
    ) throws IROCatalogExternalExternalTrueGetAllRecoveryPointsForMachineCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetAllRecoveryPointsForMachineCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetAllRecoveryPointsForDataSourceResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForDataSource", output = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForDataSourceResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetAllRecoveryPointsForDataSourceCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForDataSourceCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetAllRecoveryPointsForDataSourceCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForDataSourceCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetAllRecoveryPointsForDataSource", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRecoveryPointsForDataSource")
    @WebMethod(operationName = "GetAllRecoveryPointsForDataSource", action = "http://tempuri.org/IROCatalogExternal/GetAllRecoveryPointsForDataSource")
    @ResponseWrapper(localName = "GetAllRecoveryPointsForDataSourceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRecoveryPointsForDataSourceResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.RecoveryPointInfoResponse getAllRecoveryPointsForDataSource(
        @WebParam(name = "dataSourceArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.GetInfoForMachineArgs dataSourceArgs
    ) throws IROCatalogExternalExternalTrueGetAllRecoveryPointsForDataSourceCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetAllRecoveryPointsForDataSourceCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/AddMetadataNameValue", output = "http://tempuri.org/IROCatalogExternal/AddMetadataNameValueResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueAddMetadataNameValueCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddMetadataNameValueCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueAddMetadataNameValueCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddMetadataNameValueCloudServiceFaultFault")})
    @RequestWrapper(localName = "AddMetadataNameValue", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddMetadataNameValue")
    @WebMethod(operationName = "AddMetadataNameValue", action = "http://tempuri.org/IROCatalogExternal/AddMetadataNameValue")
    @ResponseWrapper(localName = "AddMetadataNameValueResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddMetadataNameValueResponse")
    public void addMetadataNameValue(
        @WebParam(name = "metaDataNameValue", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.AddMDSetArgs metaDataNameValue
    ) throws IROCatalogExternalExternalTrueAddMetadataNameValueCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueAddMetadataNameValueCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/AddDsVolumeReplicaMap", output = "http://tempuri.org/IROCatalogExternal/AddDsVolumeReplicaMapResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueAddDsVolumeReplicaMapCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddDsVolumeReplicaMapCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueAddDsVolumeReplicaMapCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddDsVolumeReplicaMapCloudServiceFaultFault")})
    @RequestWrapper(localName = "AddDsVolumeReplicaMap", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddDsVolumeReplicaMap")
    @WebMethod(operationName = "AddDsVolumeReplicaMap", action = "http://tempuri.org/IROCatalogExternal/AddDsVolumeReplicaMap")
    @ResponseWrapper(localName = "AddDsVolumeReplicaMapResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddDsVolumeReplicaMapResponse")
    public void addDsVolumeReplicaMap(
        @WebParam(name = "dsVolRepMap", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.ArrayOfAddDsVolumeReplicaMap dsVolRepMap
    ) throws IROCatalogExternalExternalTrueAddDsVolumeReplicaMapCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueAddDsVolumeReplicaMapCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetAllPolicyIdsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetAllPolicyIds", output = "http://tempuri.org/IROCatalogExternal/GetAllPolicyIdsResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetAllPolicyIdsCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllPolicyIdsCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetAllPolicyIdsCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllPolicyIdsCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetAllPolicyIds", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPolicyIds")
    @WebMethod(operationName = "GetAllPolicyIds", action = "http://tempuri.org/IROCatalogExternal/GetAllPolicyIds")
    @ResponseWrapper(localName = "GetAllPolicyIdsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPolicyIdsResponse")
    public com.windowscloudbackup.cloudcommon.v2011_09.ArrayOfEntityId getAllPolicyIds(
        @WebParam(name = "machineArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.GetInfoForMachineArgs machineArgs
    ) throws IROCatalogExternalExternalTrueGetAllPolicyIdsCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetAllPolicyIdsCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/AddRPVolumeReplicaMapInfo", output = "http://tempuri.org/IROCatalogExternal/AddRPVolumeReplicaMapInfoResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueAddRPVolumeReplicaMapInfoCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddRPVolumeReplicaMapInfoCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueAddRPVolumeReplicaMapInfoCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddRPVolumeReplicaMapInfoCloudServiceFaultFault")})
    @RequestWrapper(localName = "AddRPVolumeReplicaMapInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRPVolumeReplicaMapInfo")
    @WebMethod(operationName = "AddRPVolumeReplicaMapInfo", action = "http://tempuri.org/IROCatalogExternal/AddRPVolumeReplicaMapInfo")
    @ResponseWrapper(localName = "AddRPVolumeReplicaMapInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRPVolumeReplicaMapInfoResponse")
    public void addRPVolumeReplicaMapInfo(
        @WebParam(name = "rpVolumeReplicaInfo", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.ArrayOfAddRPVolumeReplicaMap rpVolumeReplicaInfo
    ) throws IROCatalogExternalExternalTrueAddRPVolumeReplicaMapInfoCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueAddRPVolumeReplicaMapInfoCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetAllPoliciesResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetAllPolicies", output = "http://tempuri.org/IROCatalogExternal/GetAllPoliciesResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetAllPoliciesCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllPoliciesCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetAllPoliciesCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllPoliciesCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetAllPolicies", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPolicies")
    @WebMethod(operationName = "GetAllPolicies", action = "http://tempuri.org/IROCatalogExternal/GetAllPolicies")
    @ResponseWrapper(localName = "GetAllPoliciesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPoliciesResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ArrayOfGetPolicyInfoArgs getAllPolicies(
        @WebParam(name = "machineArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.GetInfoForMachineArgs machineArgs
    ) throws IROCatalogExternalExternalTrueGetAllPoliciesCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetAllPoliciesCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetRPVolumeReplicaMapInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetRPVolumeReplicaMapInfo", output = "http://tempuri.org/IROCatalogExternal/GetRPVolumeReplicaMapInfoResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetRPVolumeReplicaMapInfoCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetRPVolumeReplicaMapInfoCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetRPVolumeReplicaMapInfoCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetRPVolumeReplicaMapInfoCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetRPVolumeReplicaMapInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRPVolumeReplicaMapInfo")
    @WebMethod(operationName = "GetRPVolumeReplicaMapInfo", action = "http://tempuri.org/IROCatalogExternal/GetRPVolumeReplicaMapInfo")
    @ResponseWrapper(localName = "GetRPVolumeReplicaMapInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRPVolumeReplicaMapInfoResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ArrayOfGetRPVolumeReplicaMapResponse getRPVolumeReplicaMapInfo(
        @WebParam(name = "entity", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.protection.v2011_09.GetEntityInformationArgs entity
    ) throws IROCatalogExternalExternalTrueGetRPVolumeReplicaMapInfoCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetRPVolumeReplicaMapInfoCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetDsVolumeReplicaMapResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetDsVolumeReplicaMap", output = "http://tempuri.org/IROCatalogExternal/GetDsVolumeReplicaMapResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetDsVolumeReplicaMapCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetDsVolumeReplicaMapCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetDsVolumeReplicaMapCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetDsVolumeReplicaMapCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetDsVolumeReplicaMap", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDsVolumeReplicaMap")
    @WebMethod(operationName = "GetDsVolumeReplicaMap", action = "http://tempuri.org/IROCatalogExternal/GetDsVolumeReplicaMap")
    @ResponseWrapper(localName = "GetDsVolumeReplicaMapResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDsVolumeReplicaMapResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ArrayOfGetDsVolumeReplicaMap getDsVolumeReplicaMap(
        @WebParam(name = "entity", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.protection.v2011_09.GetEntityInformationArgs entity
    ) throws IROCatalogExternalExternalTrueGetDsVolumeReplicaMapCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetDsVolumeReplicaMapCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/DeletePolicyForMachine", output = "http://tempuri.org/IROCatalogExternal/DeletePolicyForMachineResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueDeletePolicyForMachineCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/DeletePolicyForMachineCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueDeletePolicyForMachineCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/DeletePolicyForMachineCloudServiceFaultFault")})
    @RequestWrapper(localName = "DeletePolicyForMachine", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeletePolicyForMachine")
    @WebMethod(operationName = "DeletePolicyForMachine", action = "http://tempuri.org/IROCatalogExternal/DeletePolicyForMachine")
    @ResponseWrapper(localName = "DeletePolicyForMachineResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeletePolicyForMachineResponse")
    public void deletePolicyForMachine(
        @WebParam(name = "deletePolicyInfo", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.DeletePolicyInfoArgs deletePolicyInfo
    ) throws IROCatalogExternalExternalTrueDeletePolicyForMachineCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueDeletePolicyForMachineCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/UpdateDatasourceVolumeClientStamp", output = "http://tempuri.org/IROCatalogExternal/UpdateDatasourceVolumeClientStampResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueUpdateDatasourceVolumeClientStampCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/UpdateDatasourceVolumeClientStampCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueUpdateDatasourceVolumeClientStampCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/UpdateDatasourceVolumeClientStampCloudServiceFaultFault")})
    @RequestWrapper(localName = "UpdateDatasourceVolumeClientStamp", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateDatasourceVolumeClientStamp")
    @WebMethod(operationName = "UpdateDatasourceVolumeClientStamp", action = "http://tempuri.org/IROCatalogExternal/UpdateDatasourceVolumeClientStamp")
    @ResponseWrapper(localName = "UpdateDatasourceVolumeClientStampResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateDatasourceVolumeClientStampResponse")
    public void updateDatasourceVolumeClientStamp(
        @WebParam(name = "dsVolStampArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.UpdateDatasourceVolumeClientStampArgs dsVolStampArgs
    ) throws IROCatalogExternalExternalTrueUpdateDatasourceVolumeClientStampCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueUpdateDatasourceVolumeClientStampCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "AddRPSetInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/AddRPSetInfo", output = "http://tempuri.org/IROCatalogExternal/AddRPSetInfoResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueAddRPSetInfoCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddRPSetInfoCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueAddRPSetInfoCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddRPSetInfoCloudServiceFaultFault")})
    @RequestWrapper(localName = "AddRPSetInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRPSetInfo")
    @WebMethod(operationName = "AddRPSetInfo", action = "http://tempuri.org/IROCatalogExternal/AddRPSetInfo")
    @ResponseWrapper(localName = "AddRPSetInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRPSetInfoResponse")
    public com.windowscloudbackup.cloudcommon.v2011_09.EntityId addRPSetInfo(
        @WebParam(name = "rpSetInfo", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.RecoveryPointSetInfo rpSetInfo
    ) throws IROCatalogExternalExternalTrueAddRPSetInfoCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueAddRPSetInfoCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/DeletePolicy", output = "http://tempuri.org/IROCatalogExternal/DeletePolicyResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueDeletePolicyCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/DeletePolicyCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueDeletePolicyCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/DeletePolicyCloudServiceFaultFault")})
    @RequestWrapper(localName = "DeletePolicy", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeletePolicy")
    @WebMethod(operationName = "DeletePolicy", action = "http://tempuri.org/IROCatalogExternal/DeletePolicy")
    @ResponseWrapper(localName = "DeletePolicyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeletePolicyResponse")
    public void deletePolicy(
        @WebParam(name = "deletePolicyInfo", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.DeletePolicyInfoArgs deletePolicyInfo
    ) throws IROCatalogExternalExternalTrueDeletePolicyCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueDeletePolicyCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetAllRPForDSResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetAllRPForDS", output = "http://tempuri.org/IROCatalogExternal/GetAllRPForDSResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetAllRPForDSCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllRPForDSCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetAllRPForDSCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllRPForDSCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetAllRPForDS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRPForDS")
    @WebMethod(operationName = "GetAllRPForDS", action = "http://tempuri.org/IROCatalogExternal/GetAllRPForDS")
    @ResponseWrapper(localName = "GetAllRPForDSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRPForDSResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ArrayOfRecoveryPointInfoEx getAllRPForDS(
        @WebParam(name = "entity", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.protection.v2011_09.GetEntityInformationArgs entity
    ) throws IROCatalogExternalExternalTrueGetAllRPForDSCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetAllRPForDSCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetPolicyAndRPInfoForMachineResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetPolicyAndRPInfoForMachine", output = "http://tempuri.org/IROCatalogExternal/GetPolicyAndRPInfoForMachineResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetPolicyAndRPInfoForMachineCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetPolicyAndRPInfoForMachineCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetPolicyAndRPInfoForMachineCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetPolicyAndRPInfoForMachineCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetPolicyAndRPInfoForMachine", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPolicyAndRPInfoForMachine")
    @WebMethod(operationName = "GetPolicyAndRPInfoForMachine", action = "http://tempuri.org/IROCatalogExternal/GetPolicyAndRPInfoForMachine")
    @ResponseWrapper(localName = "GetPolicyAndRPInfoForMachineResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPolicyAndRPInfoForMachineResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.PolicyAndRPInfoResponse getPolicyAndRPInfoForMachine(
        @WebParam(name = "machineArgs", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.GetInfoForMachineArgs machineArgs
    ) throws IROCatalogExternalExternalTrueGetPolicyAndRPInfoForMachineCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetPolicyAndRPInfoForMachineCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetRPInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetRPInfo", output = "http://tempuri.org/IROCatalogExternal/GetRPInfoResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetRPInfoCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetRPInfoCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetRPInfoCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetRPInfoCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetRPInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRPInfo")
    @WebMethod(operationName = "GetRPInfo", action = "http://tempuri.org/IROCatalogExternal/GetRPInfo")
    @ResponseWrapper(localName = "GetRPInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRPInfoResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.RecoveryPointInfoEx getRPInfo(
        @WebParam(name = "entity", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.protection.v2011_09.GetEntityInformationArgs entity
    ) throws IROCatalogExternalExternalTrueGetRPInfoCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetRPInfoCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "AddRPInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/AddRPInfo", output = "http://tempuri.org/IROCatalogExternal/AddRPInfoResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueAddRPInfoCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddRPInfoCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueAddRPInfoCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddRPInfoCloudServiceFaultFault")})
    @RequestWrapper(localName = "AddRPInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRPInfo")
    @WebMethod(operationName = "AddRPInfo", action = "http://tempuri.org/IROCatalogExternal/AddRPInfo")
    @ResponseWrapper(localName = "AddRPInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRPInfoResponse")
    public com.windowscloudbackup.cloudcommon.v2011_09.EntityId addRPInfo(
        @WebParam(name = "rpInfo", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.RecoveryPointInfo rpInfo
    ) throws IROCatalogExternalExternalTrueAddRPInfoCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueAddRPInfoCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetAllEncryptionKeysResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetAllEncryptionKeys", output = "http://tempuri.org/IROCatalogExternal/GetAllEncryptionKeysResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetAllEncryptionKeysCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllEncryptionKeysCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetAllEncryptionKeysCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetAllEncryptionKeysCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetAllEncryptionKeys", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllEncryptionKeys")
    @WebMethod(operationName = "GetAllEncryptionKeys", action = "http://tempuri.org/IROCatalogExternal/GetAllEncryptionKeys")
    @ResponseWrapper(localName = "GetAllEncryptionKeysResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllEncryptionKeysResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ArrayOfEncryptionKeyEx getAllEncryptionKeys(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.ReadEncryptionKeyRequest request
    ) throws IROCatalogExternalExternalTrueGetAllEncryptionKeysCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetAllEncryptionKeysCloudServiceFaultFaultFaultMessage;

    @Action(input = "http://tempuri.org/IROCatalogExternal/UpdatePolicyInfo", output = "http://tempuri.org/IROCatalogExternal/UpdatePolicyInfoResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueUpdatePolicyInfoCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/UpdatePolicyInfoCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueUpdatePolicyInfoCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/UpdatePolicyInfoCloudServiceFaultFault")})
    @RequestWrapper(localName = "UpdatePolicyInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePolicyInfo")
    @WebMethod(operationName = "UpdatePolicyInfo", action = "http://tempuri.org/IROCatalogExternal/UpdatePolicyInfo")
    @ResponseWrapper(localName = "UpdatePolicyInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePolicyInfoResponse")
    public void updatePolicyInfo(
        @WebParam(name = "policyInfo", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.UpdatePolicyInfoArgs policyInfo
    ) throws IROCatalogExternalExternalTrueUpdatePolicyInfoCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueUpdatePolicyInfoCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetStatusResult", targetNamespace = "http://windowscloudbackup.com/CloudCommon/V2011_09")
    @Action(input = "http://windowscloudbackup.com/CloudCommon/V2011_09/IAsyncWorkResult/GetStatus", output = "http://windowscloudbackup.com/CloudCommon/V2011_09/IAsyncWorkResult/GetStatusResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetStatusCloudServiceInternalFaultFaultFaultMessage.class, value = "http://windowscloudbackup.com/CloudCommon/V2011_09/IAsyncWorkResult/GetStatusCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetStatusCloudServiceFaultFaultFaultMessage.class, value = "http://windowscloudbackup.com/CloudCommon/V2011_09/IAsyncWorkResult/GetStatusCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://windowscloudbackup.com/CloudCommon/V2011_09", className = "com.windowscloudbackup.cloudcommon.v2011_09.GetStatus")
    @WebMethod(operationName = "GetStatus", action = "http://windowscloudbackup.com/CloudCommon/V2011_09/IAsyncWorkResult/GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://windowscloudbackup.com/CloudCommon/V2011_09", className = "com.windowscloudbackup.cloudcommon.v2011_09.GetStatusResponse")
    public com.windowscloudbackup.cloudcommon.v2011_09.GenericAsyncStatusResult getStatus(
        @WebParam(name = "request", targetNamespace = "http://windowscloudbackup.com/CloudCommon/V2011_09")
        com.windowscloudbackup.cloudcommon.v2011_09.GenericAsyncStatusArgs request
    ) throws IROCatalogExternalExternalTrueGetStatusCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetStatusCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetDataSourcesInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetDataSourcesInfo", output = "http://tempuri.org/IROCatalogExternal/GetDataSourcesInfoResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetDataSourcesInfoCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetDataSourcesInfoCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetDataSourcesInfoCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetDataSourcesInfoCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetDataSourcesInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataSourcesInfo")
    @WebMethod(operationName = "GetDataSourcesInfo", action = "http://tempuri.org/IROCatalogExternal/GetDataSourcesInfo")
    @ResponseWrapper(localName = "GetDataSourcesInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataSourcesInfoResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ArrayOfDataSourceInfoEx getDataSourcesInfo(
        @WebParam(name = "dataSourcesInfo", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.GetDsArrayInfoArgs dataSourcesInfo
    ) throws IROCatalogExternalExternalTrueGetDataSourcesInfoCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetDataSourcesInfoCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "WriteEncryptionKeysResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/WriteEncryptionKeys", output = "http://tempuri.org/IROCatalogExternal/WriteEncryptionKeysResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueWriteEncryptionKeysCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/WriteEncryptionKeysCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueWriteEncryptionKeysCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/WriteEncryptionKeysCloudServiceFaultFault")})
    @RequestWrapper(localName = "WriteEncryptionKeys", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WriteEncryptionKeys")
    @WebMethod(operationName = "WriteEncryptionKeys", action = "http://tempuri.org/IROCatalogExternal/WriteEncryptionKeys")
    @ResponseWrapper(localName = "WriteEncryptionKeysResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WriteEncryptionKeysResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.WriteEncryptionKeysResponse writeEncryptionKeys(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.WriteEncryptionKeysRequest request
    ) throws IROCatalogExternalExternalTrueWriteEncryptionKeysCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueWriteEncryptionKeysCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "AddPolicyResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/AddPolicy", output = "http://tempuri.org/IROCatalogExternal/AddPolicyResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueAddPolicyCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddPolicyCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueAddPolicyCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/AddPolicyCloudServiceFaultFault")})
    @RequestWrapper(localName = "AddPolicy", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPolicy")
    @WebMethod(operationName = "AddPolicy", action = "http://tempuri.org/IROCatalogExternal/AddPolicy")
    @ResponseWrapper(localName = "AddPolicyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPolicyResponse")
    public com.windowscloudbackup.cloudcommon.v2011_09.EntityId addPolicy(
        @WebParam(name = "policyInfo", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.AddPolicyArgs policyInfo
    ) throws IROCatalogExternalExternalTrueAddPolicyCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueAddPolicyCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetReplicaResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetReplica", output = "http://tempuri.org/IROCatalogExternal/GetReplicaResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetReplicaCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetReplicaCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetReplicaCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetReplicaCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetReplica", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReplica")
    @WebMethod(operationName = "GetReplica", action = "http://tempuri.org/IROCatalogExternal/GetReplica")
    @ResponseWrapper(localName = "GetReplicaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReplicaResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ReplicaInfoEx getReplica(
        @WebParam(name = "replicaId", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.rocatalog.v2011_09.GetReplicaArgs replicaId
    ) throws IROCatalogExternalExternalTrueGetReplicaCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetReplicaCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetMetadataSetInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetMetadataSetInfo", output = "http://tempuri.org/IROCatalogExternal/GetMetadataSetInfoResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetMetadataSetInfoCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetMetadataSetInfoCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetMetadataSetInfoCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetMetadataSetInfoCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetMetadataSetInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMetadataSetInfo")
    @WebMethod(operationName = "GetMetadataSetInfo", action = "http://tempuri.org/IROCatalogExternal/GetMetadataSetInfo")
    @ResponseWrapper(localName = "GetMetadataSetInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMetadataSetInfoResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.ArrayOfMetadataSetNameValueInfoEx getMetadataSetInfo(
        @WebParam(name = "entity", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.protection.v2011_09.GetEntityInformationArgs entity
    ) throws IROCatalogExternalExternalTrueGetMetadataSetInfoCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetMetadataSetInfoCloudServiceFaultFaultFaultMessage;

    @WebResult(name = "GetDsInfoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IROCatalogExternal/GetDsInfo", output = "http://tempuri.org/IROCatalogExternal/GetDsInfoResponse", fault = {@FaultAction(className = IROCatalogExternalExternalTrueGetDsInfoCloudServiceInternalFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetDsInfoCloudServiceInternalFaultFault"), @FaultAction(className = IROCatalogExternalExternalTrueGetDsInfoCloudServiceFaultFaultFaultMessage.class, value = "http://tempuri.org/IROCatalogExternal/GetDsInfoCloudServiceFaultFault")})
    @RequestWrapper(localName = "GetDsInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDsInfo")
    @WebMethod(operationName = "GetDsInfo", action = "http://tempuri.org/IROCatalogExternal/GetDsInfo")
    @ResponseWrapper(localName = "GetDsInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDsInfoResponse")
    public com.windowscloudbackup.rocatalog.v2011_09.DataSourceInfoEx getDsInfo(
        @WebParam(name = "entity", targetNamespace = "http://tempuri.org/")
        com.windowscloudbackup.protection.v2011_09.GetEntityInformationArgs entity
    ) throws IROCatalogExternalExternalTrueGetDsInfoCloudServiceInternalFaultFaultFaultMessage, IROCatalogExternalExternalTrueGetDsInfoCloudServiceFaultFaultFaultMessage;
}
