package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.microsoft.schemas._2006._04.mex.IMetadataExchange;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-11T20:29:56.291+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "ROCatalogExternalService", 
                  wsdlLocation = "https://pod01-prot2.wus.backup.windowsazure.com/ROCatalogExternalService.svc",
                  targetNamespace = "http://tempuri.org/") 
public class ROCatalogExternalService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ROCatalogExternalService");
    public final static QName BasicHttpBindingIROCatalogExternalExternalTrue = new QName("http://tempuri.org/", "BasicHttpBindingIROCatalogExternalExternal_True");
    public final static QName MetadataExchangeHttpsBindingIMetadataExchange = new QName("http://tempuri.org/", "MetadataExchangeHttpsBinding_IMetadataExchange");
    static {
        URL url = null;
        try {
            url = new URL("https://pod01-prot2.wus.backup.windowsazure.com/ROCatalogExternalService.svc");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ROCatalogExternalService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://pod01-prot2.wus.backup.windowsazure.com/ROCatalogExternalService.svc");
        }
        WSDL_LOCATION = url;
    }

    public ROCatalogExternalService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ROCatalogExternalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ROCatalogExternalService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ROCatalogExternalService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ROCatalogExternalService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ROCatalogExternalService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IROCatalogExternalExternalTrue
     */
    @WebEndpoint(name = "BasicHttpBindingIROCatalogExternalExternal_True")
    public IROCatalogExternalExternalTrue getBasicHttpBindingIROCatalogExternalExternalTrue() {
        return super.getPort(BasicHttpBindingIROCatalogExternalExternalTrue, IROCatalogExternalExternalTrue.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IROCatalogExternalExternalTrue
     */
    @WebEndpoint(name = "BasicHttpBindingIROCatalogExternalExternal_True")
    public IROCatalogExternalExternalTrue getBasicHttpBindingIROCatalogExternalExternalTrue(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIROCatalogExternalExternalTrue, IROCatalogExternalExternalTrue.class, features);
    }
    /**
     *
     * @return
     *     returns IMetadataExchange
     */
    @WebEndpoint(name = "MetadataExchangeHttpsBinding_IMetadataExchange")
    public IMetadataExchange getMetadataExchangeHttpsBindingIMetadataExchange() {
        return super.getPort(MetadataExchangeHttpsBindingIMetadataExchange, IMetadataExchange.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMetadataExchange
     */
    @WebEndpoint(name = "MetadataExchangeHttpsBinding_IMetadataExchange")
    public IMetadataExchange getMetadataExchangeHttpsBindingIMetadataExchange(WebServiceFeature... features) {
        return super.getPort(MetadataExchangeHttpsBindingIMetadataExchange, IMetadataExchange.class, features);
    }

}
