package com.microsoft.schemas._2006._04.mex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-11T20:29:56.286+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/2006/04/mex", name = "IMetadataExchange")
@XmlSeeAlso({org.tempuri.ObjectFactory.class, com.windowscloudbackup.protection.v2011_09.ObjectFactory.class, utils.accessmanager.dls.enterprisestorage.internal.microsoft.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_internal_cloudbackup_common_cloudcommon.ObjectFactory.class, com.microsoft.schemas.message.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.windowscloudbackup.cloudcommon.v2011_09.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_internal_cloudbackup_common_async.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_internal_cloudbackup_common_rocatalog.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_internal_cloudbackup_common.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, com.windowscloudbackup.rocatalog.v2011_09.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IMetadataExchange {

    @WebResult(name = "GetResult", targetNamespace = "", partName = "GetResult")
    @Action(input = "http://schemas.xmlsoap.org/ws/2004/09/transfer/Get", output = "http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse")
    @WebMethod(operationName = "Get", action = "http://schemas.xmlsoap.org/ws/2004/09/transfer/Get")
    public com.microsoft.schemas.message.MessageBody get(
        @WebParam(partName = "request", name = "request", targetNamespace = "")
        com.microsoft.schemas.message.MessageBody request
    );
}
