
package com.microsoft.schemas._2006._04.mex;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import org.tempuri.ROCatalogExternalService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-12-11T20:29:55.699+08:00
 * Generated source version: 3.0.2
 * 
 */
public final class IMetadataExchange_MetadataExchangeHttpsBindingIMetadataExchange_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "ROCatalogExternalService");

    private IMetadataExchange_MetadataExchangeHttpsBindingIMetadataExchange_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ROCatalogExternalService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ROCatalogExternalService ss = new ROCatalogExternalService(wsdlURL, SERVICE_NAME);
        
        IMetadataExchange port = ss.getMetadataExchangeHttpsBindingIMetadataExchange();  
        
        {
        System.out.println("Invoking get...");
        com.microsoft.schemas.message.MessageBody _get_request = null;
        com.microsoft.schemas.message.MessageBody _get__return = port.get(_get_request);
        System.out.println("get.result=" + _get__return);


        }

        System.exit(0);
    }

}
