//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macrodeek.StarDustModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AzureImage
    {
        public int Id { get; set; }
        public string BucketName { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int IsPorn { get; set; }
        public int HotScore { get; set; }
        public int NormalScore { get; set; }
        public int PornScore { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
