//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macrodeek.StarDustModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Macrodeek.MacrodeekCommon;
    
    public partial class StarDustGoldModelContainer : DbContext
    {
        public StarDustGoldModelContainer()
            : base(AppSettingsProvider.GetSetting("StarDustGoldModelContainer"))
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AzureImage> AzureImages { get; set; }
        public virtual DbSet<ImageBucket> ImageBuckets { get; set; }
        public virtual DbSet<ImageBucketUsage> ImageBucketUsages { get; set; }
    }
}
