(function(n){MsPortalFx.Data.Metadata.setTypesMetadata(n)})({namespaces:["Microsoft.Portal.HubsExtension.Providers.WhatsNew",
"Microsoft.Portal.HubsExtension.ServicesHealth.Models"],metadata:[{name:{namespaceIndex:0,name:"WhatsNewItem"},
properties:{title:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0},content:{typeIndex:
-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0},published:{typeIndex:-1,isArray:!1,isDate:!1,
trackEdits:!0,persistEdits:!0},uri:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0}},
idProperties:[],entityType:!1,hasGloballyUniqueId:!1},{name:{namespaceIndex:1,name:"AzureRegion"},properties:
{id:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0},name:{typeIndex:-1,isArray:!1,
isDate:!1,trackEdits:!0,persistEdits:!0},isServiceMultiRegion:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:
!0,persistEdits:!0},status:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0},children:
{typeIndex:1,isArray:!0,isDate:!1,trackEdits:!0,persistEdits:!0}},idProperties:["id"],entityType:!1,
hasGloballyUniqueId:!1},{name:{namespaceIndex:1,name:"AzureService"},properties:{id:{typeIndex:-1,isArray:
!1,isDate:!1,trackEdits:!0,persistEdits:!0},name:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:
!0},status:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0},regions:{typeIndex:3,isArray:
!0,isDate:!1,trackEdits:!0,persistEdits:!0}},idProperties:["id"],entityType:!1,hasGloballyUniqueId:!1},
{name:{namespaceIndex:1,name:"AzureServiceRegion"},properties:{id:{typeIndex:-1,isArray:!1,isDate:!1,
trackEdits:!0,persistEdits:!0},rssCode:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:
!0},serviceId:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0},regionId:{typeIndex:
-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0},name:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:
!0,persistEdits:!0},status:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0},incidents:
{typeIndex:4,isArray:!0,isDate:!1,trackEdits:!0,persistEdits:!0}},idProperties:["id"],entityType:!1,
hasGloballyUniqueId:!1},{name:{namespaceIndex:1,name:"AzureServiceRegionIncident"},properties:{title:
{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0},messages:{typeIndex:5,isArray:!0,isDate:
!1,trackEdits:!0,persistEdits:!0}},idProperties:[],entityType:!1,hasGloballyUniqueId:!1},{name:{namespaceIndex:
1,name:"AzureServiceRegionIncidentMessage"},properties:{time:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:
!0,persistEdits:!0},details:{typeIndex:-1,isArray:!1,isDate:!1,trackEdits:!0,persistEdits:!0}},idProperties:
[],entityType:!1,hasGloballyUniqueId:!1}],rootTypeIndex:5})