//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macrodeek.StarDustModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageBucketUsage
    {
        public int Id { get; set; }
        public string BucketName { get; set; }
        public long TotalStorage { get; set; }
        public long ThroughPut { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
