//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macrodeek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalentCandidate
    {
        public long Id { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public string Location { get; set; }
        public string Login { get; set; }
        public string Name { get; set; }
        public string Followers { get; set; }
        public string ReposUrl { get; set; }
        public string FollowersUrl { get; set; }
        public long CacheTotalCommits { get; set; }
        public long CalculatingTotalCommits { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
